language: minimal
sudo: false

before_deploy:
- openssl aes-256-cbc -K $encrypted_fb168f48dc0a_key -iv $encrypted_fb168f48dc0a_iv
  -in travis_service_account_key.json.enc -out travis_service_account_key.json -d
deploy:
  provider: gae
  project: page-perso-211118
  version: main
  keyfile: travis_service_account_key.json
  skip_cleanup: true
  verbosity: warning
  on: master
