service: default
runtime: python27
api_version: 1
threadsafe: yes
instance_class: F1
automatic_scaling:
  max_instances: 1

default_expiration: "10m"

handlers:
- url: /
  static_files: index.html
  upload: index.html
  secure: always

- url: /service-worker.js
  static_files: service-worker.js
  upload: service-worker.js
  secure: always
  expiration: "0s"

- url: /manifest.json
  static_files: manifest.json
  upload: manifest.json
  secure: always
  expiration: "0s"

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
  secure: always
  expiration: "30d"

- url: /assets/app
  static_dir: assets/app
  secure: always

- url: /assets/image
  static_dir: assets/image
  secure: always
  expiration: "5d"

- url: /assets/icons
  static_dir: assets/icons
  secure: always
  expiration: "10d"

- url: /.*
  static_files: 404.html
  upload: 404.html
  secure: always
  expiration: "1d"


skip_files:
- .idea/
- .vscode
- .git/
- .editorconfig
- .gitignore
- .travis.yml
- README.md
- travis_service_account_key.json
- travis_service_account_key.json.enc
