service: default
runtime: python27
api_version: 1
threadsafe: yes
instance_class: F1
automatic_scaling:
  max_instances: 1

default_expiration: "10m"

handlers:
- url: /
  static_files: index.html
  upload: index.html
  secure: always

- url: /public/app
  static_dir: public/app
  secure: always

- url: /public/image
  static_dir: public/image
  secure: always
  expiration: "5d"

- url: /.*
  static_files: 404.html
  upload: 404.html
  secure: always
  expiration: "1d"


skip_files:
- .idea/
- .vscode
- .git/
- .editorconfig
- .gitignore
- .travis.yml
- README.md
- travis_service_account_key.json
- travis_service_account_key.json.enc
