service: default
runtime: python27
api_version: 1
threadsafe: yes
instance_class: F1
automatic_scaling:
  max_instances: 1

default_expiration: "10m"

handlers:
- url: /
  static_files: index.html
  upload: index.html
  secure: always

- url: /public/(.*\.(jpg|ico))$
  static_files: public/\1
  upload: public/.*\.(jpg|ico)$
  secure: always
  expiration: "5d"

- url: /public/(.*)
  static_files: public/\1
  upload: /public/.*
  secure: always

skip_files:
- .idea/
- .vscode
- .git/
- .editorconfig
- .gitignore
- .travis.yml
- README.md
- travis_service_account_key.json
- travis_service_account_key.json.enc
