service: default
runtime: python27
api_version: 1
threadsafe: yes
instance_class: F1
automatic_scaling:
  max_instances: 1

handlers:
- url: /
  static_files: index.html
  upload: index.html
  secure: always

- url: /public
  static_dir: public
  secure: always

skip_files:
- .idea/
- .vscode
- .git/
- .editorconfig
- .gitignore
- .travis.yml
- README.md
- travis_service_account_key.json
- travis_service_account_key.json.enc
